version: '3.8'

services:
  text-summarizer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=host.docker.internal:0.0
      - XAUTHORITY=/root/.Xauthority
    command: bash -c "touch /root/.Xauthority && xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f /root/.Xauthority nmerge - && python text_summarizer.py"
